name: CI to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
    - uses: actions/checkout@v2
    
    - name: Linelint
      uses: fernandrone/linelint@0.0.4

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
          install: true
          # config: .github/buildkitd.toml

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: |
          ashish1981/s390x-base-notebook:latest 
          
        # build on feature branches, push only on main branch
        # push: ${{ github.ref == 'refs/heads/main' }}

    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}
